objects/Inspection__c.object
<CustomObject>
    <fields>
        <fullName>Completed_Date__c</fullName>
        <label>Completed Date</label>
        <type>Date</type>
    </fields>
    <label>Inspection</label>
    <nameField>
        <displayFormat>Ins-{00000000}</displayFormat>
        <label>Id Inspection</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inspections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>Inspection__c</fullName>
        <label>Inspection</label>
        <referenceTo>Inspection__c</referenceTo>
        <relationshipLabel>Surveys</relationshipLabel>
        <relationshipName>Surveys</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <displayFormat>Survey-{0000000}</displayFormat>
        <label>Id Survey</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Survey_Response__c.object
<CustomObject>
    <fields>
        <fullName>Answered__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Answered</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Passed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Passed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Responses</relationshipLabel>
        <relationshipName>Responses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Response</label>
    <nameField>
        <displayFormat>Res-{0000000}</displayFormat>
        <label>Id Response</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/InspectionServices.cls
global class InspectionServices {
    
	webservice static string completeSurveys(String ids) {
    	if (ids == null) {
    		return 'Error: you must provide an id';	
    	}
    	
        List<string> iids = ids.split(',');
        return complete([SELECT Passed__c, Answered__c, Survey__r.Inspection__c 
                         FROM Survey_Response__c 
                         WHERE Survey__r.Inspection__c in :iids]);
    }
    
    webservice static string completeAllPendingSurveys() {
		return complete([SELECT Passed__c, Answered__c, Survey__r.Inspection__c 
                         FROM Survey_Response__c 
                         WHERE Survey__r.Inspection__r.Completed_Date__c = null]);                
    }
    
    private static string complete(List<Survey_Response__c> resps) {
        Set<id> inspectionIds = new Set<id>();
        
        for (Survey_Response__c r : resps) {
            r.Passed__c = Math.random() > .33;
            r.Answered__c = true;
            inspectionIds.add(r.Survey__r.Inspection__c);
        }
        
        update(resps);
        
        List<Inspection__c> inspections = [Select Completed_Date__c  from Inspection__c where id in :inspectionIds];
        for (Inspection__c s : inspections) {
            s.Completed_Date__c  = Date.today();
        }
        
        try {
	        update (inspections);
            return inspections.size() + ' inspections completed sucessfully.';
        } catch (Exception e) {
            return 'Error: ' + e;
        }
    }
}