objects/Inspection__c.object
<CustomObject>
    <fields>
        <fullName>Completed_Date__c</fullName>
        <label>Completed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Store__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Store</label>
        <referenceTo>Store__c</referenceTo>
        <relationshipName>Inspections</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Inspection</label>
    <nameField>
        <displayFormat>Ins-{00000000}</displayFormat>
        <label>Id Inspection</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inspections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Store__c.object
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>Inspection__c</fullName>
        <label>Inspection</label>
        <referenceTo>Inspection__c</referenceTo>
        <relationshipLabel>Surveys</relationshipLabel>
        <relationshipName>Surveys</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <displayFormat>Survey-{0000000}</displayFormat>
        <label>Id Survey</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Survey_Question__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Store Appearance</fullName>
                </value>
                <value>
                    <fullName>Skills And Knowledge</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Survey Question</label>
    <nameField>
        <displayFormat>SQ-{000000}</displayFormat>
        <label>Id Survey Question</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Survey_Response__c.object
<CustomObject>
    <fields>
        <fullName>Answered__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Answered</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Passed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Passed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <referenceTo>Survey_Question__c</referenceTo>
        <relationshipLabel>Responses</relationshipLabel>
        <relationshipName>Responses</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Responses</relationshipLabel>
        <relationshipName>Responses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Response</label>
    <nameField>
        <displayFormat>Res-{0000000}</displayFormat>
        <label>Id Response</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/SurveyController.cls
public class SurveyController {
    public List<String> categories {get; set;}
    public Inspection__c inspection {get; set;}
    public Survey__c survey {get; set;}
    public List<Survey_Response__c> responses {get; set;}
    public String answeredResponses {get; set;}
    public Attachment image {get; set;}
    public String state {get; set;}
    
    public SurveyController() {
        image = new Attachment();
        answeredResponses = '';
        String inspectionId = ApexPages.currentPage().getParameters().get('insp');
        inspection = [SELECT Id, Completed_Date__c, (SELECT Id FROM Surveys__r), Store__c FROM Inspection__c WHERE Id =:inspectionId  LIMIT 1];
        prepareCategories();
    }
    
    private void prepareCategories() {
        //Get all categories
        Schema.DescribeFieldResult fieldResult = Survey_Question__c.Category__c.getDescribe();
        List<Schema.PicklistEntry> entries = fieldResult.getPicklistValues();
        categories = new List<String>();
        for (Schema.PicklistEntry entry : entries) {
            categories.add(entry.value);
        }
        
        //categories.sort();
    }
    
    public void prepareData() {
        if (inspection.surveys__r == null || inspection.surveys__r.size() == 0) {
            survey = new Survey__c();
            survey.Inspection__c = inspection.id;

            insert(survey);

            List<Survey_Question__c> questions = [SELECT Id FROM Survey_Question__c ORDER BY Order__c];
            responses = new List<Survey_Response__c>();
            for (Survey_Question__c q : questions) {
                Survey_Response__c resp = new Survey_Response__c();
                resp.Survey__c = survey.id;
                resp.Question__c = q.id;
                responses.add(resp);
            }

            insert(responses);   

            reloadResponses();
        } else {
            survey = inspection.surveys__r[0];
            reloadResponses();
            if (responses.size() == 0) {
                delete(survey);
                inspection = [SELECT Id, Completed_Date__c, (SELECT Id FROM Surveys__r), Store__c FROM Inspection__c WHERE Id =:inspection.Id  LIMIT 1];                        
                prepareData();
            }
        }
    }
    
    private void reloadResponses() {
            responses = [SELECT Id, Passed__c, Comments__c, Answered__c,
                            Question__c, Question__r.Question__c, Question__r.Category__c, Question__r.Order__c,
                            (SELECT id FROM Attachments)
                         FROM Survey_Response__c
                         WHERE Survey__c = :survey.id
                         ORDER BY Question__r.Order__c];                         

    }

    private void checkAnswered() {
        Set<String> ids = new Set<String>(answeredResponses.split(','));
        for (Survey_Response__c response : responses) {
            if (ids.contains(response.id) && !response.answered__c) {
                response.answered__c = true;
            }
        }
    }
    
    public Integer getRespondedPercentage() {
        if (responses != null) {
            Decimal count = 0;
            for (Survey_Response__c response : responses) {
                if (response.answered__c) {
                    count++;
                }
            }
            
            return Math.round((count / responses.size()) * 100);
        }
        
        return -1;
    }
    
    public void save() {
        checkAnswered();
        update(responses);
        
        for (Survey_Response__c response : responses) {
            if (response.answered__c == false) {
                return;
            }
        }
        
        inspection.completed_date__c = Date.today();
        update(inspection);
    }

    public void upload() {
        if (image.parentId != null && image.body != null && image.name != null) {
            insert(image);
            image = new Attachment();

            reloadResponses();
        }
    }
}