objects/Inspection__c.object
<CustomObject>
    <fields>
        <fullName>Store__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Store</label>
        <referenceTo>Store__c</referenceTo>
        <relationshipName>Inspections</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Inspection</label>
    <nameField>
        <displayFormat>Ins-{00000000}</displayFormat>
        <label>Id Inspection</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inspections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Store__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Store</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Survey__c.object
<CustomObject>
    <fields>
        <fullName>Inspection__c</fullName>
        <label>Inspection</label>
        <referenceTo>Inspection__c</referenceTo>
        <relationshipLabel>Surveys</relationshipLabel>
        <relationshipName>Surveys</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <displayFormat>Survey-{0000000}</displayFormat>
        <label>Id Survey</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Survey_Question__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Store Appearance</fullName>
                </value>
                <value>
                    <fullName>Skills And Knowledge</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Survey Question</label>
    <nameField>
        <displayFormat>SQ-{000000}</displayFormat>
        <label>Id Survey Question</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Survey_Response__c.object
<CustomObject>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <referenceTo>Survey_Question__c</referenceTo>
        <relationshipLabel>Responses</relationshipLabel>
        <relationshipName>Responses</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Survey__c</fullName>
        <label>Survey</label>
        <referenceTo>Survey__c</referenceTo>
        <relationshipLabel>Responses</relationshipLabel>
        <relationshipName>Responses</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Response</label>
    <nameField>
        <displayFormat>Res-{0000000}</displayFormat>
        <label>Id Response</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/SurveyControllerTest.cls
@isTest(SeeAllData=True)
private class SurveyControllerTest {

	private static String inspectionId;
	
	@isTest static void testSurveyLoadSuccess() {
		
		PageReference pageRef = Page.SurveyPage;
		Test.setCurrentPage( pageRef );

		// initialize data
		initTestData();

		// inject the inspection id in to the page
		pageRef.getParameters().put( 'insp', inspectionId );

		// start testing
		Test.startTest();
		
		SurveyController c = new SurveyController();
		// Categories is automatically instantiated.
		//c.prepareCategories();
		c.prepareData();

		Test.stopTest();

		System.assert(true);

	}
	
	@isTest static void testPrepareDataNoSurveys() {
		
		PageReference pageRef = Page.SurveyPage;
		Test.setCurrentPage( pageRef );

		// initialize data
		initTestDataNoSurvey();

		// inject the inspection id in to the page
		pageRef.getParameters().put( 'insp', inspectionId );

		Test.startTest();

		SurveyController c = new SurveyController();
		// prep data before trying to save so that the controller is initialized.
		c.prepareData();

		Test.stopTest();
	}

	@isTest static void testSave() {

		PageReference pageRef = Page.SurveyPage;
		Test.setCurrentPage( pageRef );

		// initialize data
		initTestData();

		// inject the inspection id in to the page
		pageRef.getParameters().put( 'insp', inspectionId );

		Test.startTest();

		SurveyController c = new SurveyController();
		// prep data before trying to save so that the controller is initialized.
		c.prepareData();
		// Save what was prepped. DB will rollback automatically
		c.save();
		
		// Stop testing
		Test.stopTest();
		// Assert result
		System.assert( true );
	}

	@isTest static void getRespondedPercentage() {

		PageReference pageRef = Page.SurveyPage;
		Test.setCurrentPage( pageRef );

		// initialize data
		initTestData();

		// inject the inspection id in to the page
		pageRef.getParameters().put( 'insp', inspectionId );

		Test.startTest();

		SurveyController c = new SurveyController();
		Integer result = c.getRespondedPercentage();

		Test.stopTest();

		System.assertEquals( result, -1 );

	}

	@isTest static void testUpload() {

		PageReference pageRef = Page.SurveyPage;
		Test.setCurrentPage( pageRef );

		// initialize data
		initTestData();

		// inject the inspection id in to the page
		pageRef.getParameters().put( 'insp', inspectionId );

		Test.startTest();
		
		SurveyController c = new SurveyController();
		c.upload();

		Test.stopTest();

	}
	
	private static void initTestData() {

		// New Store
		Store__c store1 = new Store__c( Address__c = 'address', City__c = 'city', Country__c = 'country', Postal_Code__c = Decimal.valueOf(123456), Region__c = 'region' );
		insert store1;
		
		// New inspection
		Inspection__c i1 = new Inspection__c();
		//i1.Name = 'test inspection';
		i1.Store__c = store1.Id;
		insert i1;
		inspectionId = i1.Id;

		// New Survey
		Survey__c s1 = new Survey__c( Inspection__c = i1.Id );
		//s1.Name = 'test survey';
		insert s1;

		// New Survey Question
		Survey_Question__c sq1 = new Survey_Question__c( Order__c = Decimal.valueOf(999), Question__c = 'asdf' );
		insert sq1;

		// New Survey Response
		Survey_Response__c sr1 = new Survey_Response__c( Survey__c = s1.Id, Question__c = sq1.Id );
		//sr1.Name = 'test response 1';
		//sr1.Category__c = 'test category 1';
		insert sr1;

	}

	private static void initTestDataNoSurvey() {

		// New Store
		Store__c store1 = new Store__c( Address__c = 'address', City__c = 'city', Country__c = 'country', Postal_Code__c = Decimal.valueOf(123456), Region__c = 'region' );
		insert store1;
		
		// New inspection
		Inspection__c i1 = new Inspection__c();
		//i1.Name = 'test inspection';
		i1.Store__c = store1.Id;
		insert i1;
		inspectionId = i1.Id;

		// New Survey //
		//Survey__c s1 = new Survey__c( Inspection__c = i1.Id );
		//s1.Name = 'test survey';
		//insert s1;

		// New Survey Question
		Survey_Question__c sq1 = new Survey_Question__c( Order__c = Decimal.valueOf(999), Question__c = 'asdf' );
		insert sq1;

		// New Survey Response
		//Survey_Response__c sr1 = new Survey_Response__c( Survey__c = s1.Id, Question__c = sq1.Id );
		//sr1.Name = 'test response 1';
		//sr1.Category__c = 'test category 1';
		//insert sr1;

	}
}